###########################################################################
# Developer
developerId=rubensgomes
developerName=Rubens Gomes
developerEmail=rubens.s.gomes@gmail.com

###########################################################################
# License
license=The Apache License, Version 2.0
licenseUrl=http://www.apache.org/licenses/LICENSE-2.0.txt

###########################################################################
# Personal GitHub repo used to store Maven packages
mavenRepoPackages=https://maven.pkg.github.com/rubensgomes-org/mvn-pkgs

###########################################################################
# SonarQube properties
sonar.projectKey=@SONAR_PROJECT_KEY@
sonar.organization=@SONAR_ORGANIZATION@
sonar.host.url=https://sonarcloud.io
# SONAR_TOKEN must be defined as an environment variable

###########################################################################
# Release properties
release.useAutomaticVersion=true

###########################################################################
# Gradle properties
# NOTE: Plugin 'net.researchgate.release' does NOT work with configuration-cache.
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.console=verbose
org.gradle.logging.level=info
