artifactId=spring-blueprint
group=com.rubensgomes
description=Blueprint Spring Boot Java project to demonstrate gradle, CICD, design patterns...
title=Spring Boot Java Blueprint Project
mainClass=com.rubensgomes.blueprint.App

# version must end in SNAPSHOT for release plugin to work due to bug reported at:
# https://stackoverflow.com/questions/79675543/gradle-release-plugin-not-merging-main-to-release
version=0.0.3

###########################################################################
# SCM
scmConnection=scm:git:https://github.com/rubensgomes-org/spring-blueprint.git
scmUrl=https://github.com/rubensgomes-org/spring-blueprint

