# debug flag used inside build.gradle.kts
debug=true
artifactId=spring-blueprint
group=com.rubensgomes
description=Sample Spring Boot Java Hello World Web Application
title=Sample Spring Boot Java App
mainClass=com.rubensgomes.blueprint.App

# version must end in SNAPSHOT for release plugin to work due to bug reported at:
# https://stackoverflow.com/questions/79675543/gradle-release-plugin-not-merging-main-to-release
version=0.0.1-SNAPSHOT

###########################################################################
# SCM
scmConnection=scm:git:https://github.com/rubensgomes-org/spring-blueprint.git
scmUrl=https://github.com/rubensgomes-org/spring-blueprint

